M48
; DRILL file {KiCad 8.0.0} date 2024-03-18T20:15:56-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-18T20:15:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C5.300
%
G90
G05
T1
X60.538Y-52.76
X60.538Y-162.636
X121.58Y-52.756
X121.58Y-162.636
M30
